import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";

import { internals } from "../../lib/cli.mjs";

const CLI = join(internals.PACKAGE_ROOT, "bin", "shipproof.mjs");
const CONFIG = join(internals.PACKAGE_ROOT, "examples", "capacity", "shipproof.config.json");

function exportK6(targetPath) {
  return spawnSync(
    process.execPath,
    [CLI, "capacity", "--config", CONFIG, "--export-k6", targetPath, "--format", "json"],
    { encoding: "utf8", maxBuffer: 4_000_000, shell: false, windowsHide: true },
  );
}

test("generated k6 scripts are deterministic, parseable, and credential-free", (context) => {
  const probe = spawnSync(process.execPath, [CLI, "version"], {
    encoding: "utf8",
    shell: false,
    windowsHide: true,
  });
  if (probe.error?.code === "EPERM") {
    context.skip("subprocess creation is blocked by the host sandbox");
    return;
  }
  const outputDirectory = mkdtempSync(join(tmpdir(), "shipproof-k6-"));
  try {
    const firstScript = join(outputDirectory, "load-test-first.js");
    const secondScript = join(outputDirectory, "load-test-second.js");
    for (const targetPath of [firstScript, secondScript]) {
      const generated = exportK6(targetPath);
      assert.equal(generated.status, 0, generated.stderr);
    }
    const firstContent = readFileSync(firstScript, "utf8");
    assert.equal(firstContent, readFileSync(secondScript, "utf8"));

    const syntaxCheck = spawnSync(process.execPath, ["--check", firstScript], {
      encoding: "utf8",
      shell: false,
      windowsHide: true,
    });
    assert.equal(syntaxCheck.status, 0, syntaxCheck.stderr);

    assert.match(firstContent, /Generated by ShipProof .+; input digest: [0-9a-f]+/);
    assert.match(firstContent, /__ENV\["BASE_URL"\]/);
    assert.doesNotMatch(firstContent, /https?:\/\/(?!.*__ENV)/);
    assert.doesNotMatch(firstContent, /password|secret|token:\s*["'][^"']+["']/i);
  } finally {
    rmSync(outputDirectory, { recursive: true, force: true });
  }
});
